// Reads content/announcements/*.md, parses YAML frontmatter, and emits
// src/content.generated.ts — a typed module the worker imports at build time.
// Run this before `tsc` / `wrangler dev` / `wrangler deploy`.
//
// Localization: a base file `<name>.md` carries the default (English) copy.
// Sibling files `<name>.<locale>.md` (e.g. `welcome.zh.md`) supply per-locale
// title/body/link overrides, collected under the announcement's `translations`.
//
// Changelog is NOT baked in: the worker sources that live from GitHub Releases.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const contentDir = join(root, "content");
const outFile = join(root, "src", "content.generated.ts");

// BCP-47 base language, optionally with a region/script subtag (zh, zh-CN, pt-BR).
const LOCALE_SUFFIX = /^[a-z]{2}(-[A-Za-z]{2,4})?$/;

async function listMarkdown(dir) {
  try {
    const entries = await readdir(dir);
    return entries
      .filter((name) => name.endsWith(".md"))
      .map((name) => join(dir, name))
      .sort();
  } catch (err) {
    if (err && err.code === "ENOENT") return [];
    throw err;
  }
}

// Splits `welcome.zh.md` -> { stem: "welcome", locale: "zh" } and
// `welcome.md` -> { stem: "welcome", locale: null }.
function classify(path) {
  const stem = basename(path, extname(path));
  const dot = stem.lastIndexOf(".");
  if (dot > 0) {
    const suffix = stem.slice(dot + 1);
    if (LOCALE_SUFFIX.test(suffix)) return { stem: stem.slice(0, dot), locale: suffix };
  }
  return { stem, locale: null };
}

async function parseAnnouncement(path) {
  const raw = await readFile(path, "utf8");
  const { data, content } = matter(raw);
  const id = String(data.id ?? basename(path, extname(path)));
  if (!data.publishedAt) throw new Error(`announcement ${path} missing 'publishedAt' frontmatter`);
  if (!data.title) throw new Error(`announcement ${path} missing 'title' frontmatter`);
  const severity = data.severity ?? "info";
  if (!["info", "warning", "critical"].includes(severity)) {
    throw new Error(`announcement ${path} invalid 'severity' (got ${severity})`);
  }
  return {
    id,
    title: String(data.title),
    severity,
    // Coerce to RFC 3339. Markdown authors typically write date-only (YYYY-MM-DD);
    // the Go backend's time.Time unmarshaller needs a full timestamp.
    publishedAt: toIsoOrThrow(data.publishedAt, `announcement ${path} publishedAt`),
    expiresAt: data.expiresAt
      ? toIsoOrThrow(data.expiresAt, `announcement ${path} expiresAt`)
      : null,
    link: data.link ? String(data.link) : null,
    bodyMarkdown: content.trim(),
  };
}

// A locale variant only overrides text. Frontmatter `title`/`link` are
// optional; the markdown body becomes the localized `bodyMarkdown`.
async function parseTranslation(path) {
  const raw = await readFile(path, "utf8");
  const { data, content } = matter(raw);
  const translation = {};
  if (data.title) translation.title = String(data.title);
  if (content.trim()) translation.bodyMarkdown = content.trim();
  if (data.link !== undefined) translation.link = data.link ? String(data.link) : null;
  return translation;
}

function toIsoOrThrow(value, label) {
  const d = new Date(String(value));
  if (Number.isNaN(d.getTime())) throw new Error(`${label}: invalid date "${value}"`);
  return d.toISOString();
}

function byPublishedDesc(a, b) {
  return b.publishedAt.localeCompare(a.publishedAt);
}

async function main() {
  const announcementPaths = await listMarkdown(join(contentDir, "announcements"));
  const basePaths = [];
  const localePaths = [];
  for (const path of announcementPaths) {
    (classify(path).locale ? localePaths : basePaths).push(path);
  }

  const byStem = new Map();
  const announcements = await Promise.all(
    basePaths.map(async (path) => {
      const announcement = await parseAnnouncement(path);
      byStem.set(classify(path).stem, announcement);
      return announcement;
    }),
  );

  for (const path of localePaths) {
    const { stem, locale } = classify(path);
    const base = byStem.get(stem);
    if (!base) throw new Error(`announcement translation ${path} has no base '${stem}.md'`);
    const translation = await parseTranslation(path);
    base.translations = { ...base.translations, [locale]: translation };
  }

  announcements.sort(byPublishedDesc);

  const banner = [
    "// AUTO-GENERATED by scripts/build-content.mjs. Do not edit by hand.",
    "// Regenerate: `vp run update-worker#build:content`",
    "",
    'import type { Announcement } from "./types.ts";',
    "",
  ].join("\n");

  const body = [
    `export const generatedAnnouncements: Announcement[] = ${JSON.stringify(
      announcements,
      null,
      2,
    )};`,
    "",
  ].join("\n");

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, banner + body, "utf8");

  console.log(`[update-worker] wrote ${outFile} (${announcements.length} announcements)`);
}

main().catch((err) => {
  console.error("[update-worker] build-content failed:", err);
  process.exit(1);
});
