// Code generated by apps/backend/scripts/generate-wave1-web-projects.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebProjectsBadRequest = errors.New("generated web projects bad request")

type GeneratedListProjectsRequest struct {
	WorkspaceID *int64  `json:"workspace_id,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type CreateProjectRequestBody struct {
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
}

type GeneratedWave1WebProjectsHandler interface {
	ListProjects(context.Context, string, GeneratedListProjectsRequest) Wave1Response
	CreateProject(context.Context, string, CreateProjectRequestBody) Wave1Response
	GetProject(context.Context, string, int64) Wave1Response
	ArchiveProject(context.Context, string, int64) Wave1Response
	RestoreProject(context.Context, string, int64) Wave1Response
	PinProject(context.Context, string, int64) Wave1Response
	UnpinProject(context.Context, string, int64) Wave1Response
}

func registerGeneratedWave1WebProjectsRoutes(
	server *echo.Echo,
	handler GeneratedWave1WebProjectsHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/projects", func(context echo.Context) error {
		request, err := decodeListProjectsRequest(context)
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.ListProjects(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/projects", func(context echo.Context) error {
		request, err := decodeCreateProjectRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.CreateProject(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.GET("/web/v1/projects/:project_id", func(context echo.Context) error {
		projectID, ok := parsePathID(context, "project_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.GetProject(context.Request().Context(), sessionID(context), projectID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/projects/:project_id/archive", func(context echo.Context) error {
		projectID, ok := parsePathID(context, "project_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.ArchiveProject(context.Request().Context(), sessionID(context), projectID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.DELETE("/web/v1/projects/:project_id/archive", func(context echo.Context) error {
		projectID, ok := parsePathID(context, "project_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.RestoreProject(context.Request().Context(), sessionID(context), projectID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/projects/:project_id/pin", func(context echo.Context) error {
		projectID, ok := parsePathID(context, "project_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.PinProject(context.Request().Context(), sessionID(context), projectID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.DELETE("/web/v1/projects/:project_id/pin", func(context echo.Context) error {
		projectID, ok := parsePathID(context, "project_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.UnpinProject(context.Request().Context(), sessionID(context), projectID)
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeListProjectsRequest(context echo.Context) (GeneratedListProjectsRequest, error) {
	request := GeneratedListProjectsRequest{}

	if workspaceIDValue := strings.TrimSpace(context.QueryParam("workspace_id")); workspaceIDValue != "" {
		workspaceID, err := strconv.ParseInt(workspaceIDValue, 10, 64)
		if err != nil {
			return GeneratedListProjectsRequest{}, err
		}
		request.WorkspaceID = &workspaceID
	}

	if statusValue := strings.TrimSpace(context.QueryParam("status")); statusValue != "" {
		switch statusValue {
		case "all", "active", "archived":
			request.Status = &statusValue
		default:
			return GeneratedListProjectsRequest{}, errGeneratedWebProjectsBadRequest
		}
	}

	return request, nil
}

func decodeCreateProjectRequest(request *http.Request) (CreateProjectRequestBody, error) {
	type createProjectRequestBodyRaw struct {
		WorkspaceID *int64  `json:"workspace_id"`
		Name        *string `json:"name"`
	}

	var raw createProjectRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return CreateProjectRequestBody{}, err
	}
	if raw.WorkspaceID == nil || raw.Name == nil {
		return CreateProjectRequestBody{}, errGeneratedWebProjectsBadRequest
	}

	name := strings.TrimSpace(*raw.Name)
	if name == "" {
		return CreateProjectRequestBody{}, errGeneratedWebProjectsBadRequest
	}

	return CreateProjectRequestBody{
		WorkspaceID: *raw.WorkspaceID,
		Name:        name,
	}, nil
}
